module.exports = {
  content: [
    './public/stitch-desktop-lang.html',
    './src/entry-server.ts',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error': '#490106',
        primary: '#c6c6c7',
        'secondary-dim': '#9f9d9d',
        'on-tertiary-container': '#005359',
        'on-error-container': '#ff9993',
        'on-secondary-container': '#c1bfbe',
        'surface-tint': '#c6c6c7',
        'on-primary': '#3f4041',
        'secondary-fixed': '#e4e2e1',
        error: '#ee7d77',
        'secondary-fixed-dim': '#d6d4d3',
        'secondary-container': '#3c3b3b',
        'primary-dim': '#b8b9b9',
        background: '#0e0e0e',
        'on-tertiary': '#005d63',
        'tertiary-fixed': '#00eefc',
        'on-primary-fixed-variant': '#5a5c5c',
        'on-tertiary-fixed-variant': '#005e64',
        'on-secondary-fixed-variant': '#5c5b5b',
        'surface-container': '#191919',
        'on-primary-container': '#d0d0d0',
        'primary-fixed': '#e2e2e2',
        'inverse-surface': '#f9f9f9',
        tertiary: '#8ff5ff',
        'error-dim': '#bb5551',
        'primary-container': '#454747',
        'surface-container-highest': '#262626',
        'on-surface': '#e5e5e5',
        'primary-fixed-dim': '#d4d4d4',
        'on-secondary': '#202020',
        'on-background': '#e5e5e5',
        'surface-bright': '#2c2c2c',
        'surface-container-high': '#1f1f1f',
        'outline-variant': '#484848',
        'tertiary-container': '#00eefc',
        'on-primary-fixed': '#3e4040',
        'on-surface-variant': '#ababab',
        'surface-variant': '#262626',
        outline: '#757575',
        'surface-container-lowest': '#000000',
        'tertiary-dim': '#00deec',
        'surface-container-low': '#131313',
        'inverse-on-surface': '#555555',
        'error-container': '#7f2927',
        'inverse-primary': '#5e5f60',
        'on-secondary-fixed': '#3f3f3f',
        'surface-dim': '#0e0e0e',
        'tertiary-fixed-dim': '#00deec',
        'on-tertiary-fixed': '#003f43',
        surface: '#0e0e0e',
        secondary: '#9f9d9d',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk'],
        display: ['Space Grotesk'],
        body: ['Inter'],
        label: ['Space Grotesk'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
